services:
  - type: web
    name: sistema-experto-emprendedor-tdf
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
